"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['CompassDesktop.py']
DATA_FILES = ['compass_desktop.png', 'tech_card.png']
OPTIONS = {
    'packages': ['PIL'], 
    'iconfile': 'compass_desktop_icn.icns',
    'plist': {
        'CFBundleName': 'Compass Desktop',
        'CFBundleDisplayName': 'CompassDesktop',
        'CFBundleGetInfoString': "Let's users watermark desktop wallpapers with Gorham Compass usage",
        'CFBundleVersion': "0.1",
        'CFBundleShortVersionString': "0.1",
        'NSHumanReadableCopyright': u"Copyright © 2020 Ben Swift, All Rights Reserved"
    }
    }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
